# Generated by Django 3.1 on 2024-11-05 05:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=255)),
                ('admin', models.ManyToManyField(related_name='project_admin', to=settings.AUTH_USER_MODEL)),
                ('member', models.ManyToManyField(related_name='project_member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
